#ifndef ENUMVIEWTYPE_H
#define ENUMVIEWTYPE_H
typedef enum
{
    eViewMenu,
    eViewReview,
    eViewQC,
    eViewQCRule,
    eViewQCReview,
    eViewGraph,
    eViewMain,
    eViewCalibrate,
    eViewReagent,
    eViewPrint,
    eViewSetupPrint,
    eViewSetupUser,
    eViewSetupAssist,
    eViewSetupFlag,
    eViewSetupPatientInfo,
    eViewSetupDataDic,
    eViewSetupLabInfo,
    eViewSetupParameter,
    eViewSetupEquipment,
    eViewSetupCom,
    eViewSetupTouchPad,
    eViewLog,
    eViewServiceLog,
    eViewServiceMaintain,
    eViewServiceCheck,
    eViewServiceAdvancedTool,
    eViewStatusVersion,
    eViewShutDown,
    eViewMaintain,
    eViewUnknown,
    eViewNum,
}eViewType;
#endif // ENUMVIEWTYPE_H
